Feature/action mailer
NickelGit/TaskManager pull request #33
Opened 2020-06-22 06:30 UTC by NickelGit

Отправка писем. Action Mailer

2020-06-23 10:51 UTC, pn-y requested changes

2020-06-23 10:51 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +      includes([:author]).
можно сделать `includes(:author, assignee)`

2020-06-23 10:51 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +                        task_name: task.name,
Не очень консистетно кмк. У тебя вся эта инфа есть в таске, ты можешь ее вытащить в мейлере.

2020-06-23 10:51 UTC, pn-y commented on app/controllers/concerns/reset_password_helper.rb
> +  extend ActiveSupport::Concern
концерны не так используются. Перечитай доку

2020-06-23 10:51 UTC, pn-y commented on app/controllers/concerns/reset_password_helper.rb
> +  extend ActiveSupport::Concern
Бизнес логика не должна быть в контроллере

2020-06-23 10:51 UTC, pn-y commented on app/controllers/concerns/reset_password_helper.rb
> +    SecureRandom.hex(10)
А если такой токен уже существует?

2020-06-23 10:51 UTC, pn-y commented on app/controllers/concerns/reset_password_helper.rb
> +    (user.reset_password_sent_at + 24.hours) > Time.current
24 вынести в константу

2020-06-23 10:51 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +      render(json: { error: ['Email address not found. Please check and try again.'] }, status: :not_found)
Ты на самом деле не хочешь руками рендерить жсон

2020-06-23 10:51 UTC, pn-y commented on db/migrate/20200618161155_add_password_reset_columns_to_user.rb
> +    add_column :users, :reset_password_token, :string
Возможно совпадение одного токена

2020-06-23 11:39 UTC, NickelGit commented on app/controllers/api/v1/tasks_controller.rb
> +                        task_name: task.name,
А мы в мейлер уже простые типы должны передавать, или простые типы уже в сам mail() надо передавать внутри мэйлера? 
Тут просто единственный способ передать таск в мейлер целиком как объект, т.к. это delete, и из базы по id его уже вытянуть не получится.

2020-06-23 13:38 UTC, NickelGit commented on app/controllers/concerns/reset_password_helper.rb
> +  extend ActiveSupport::Concern
Перечитал, понял что концерны нужны только для сушки кода, который в нескольких местах используется. Вынес код в отдельный хелпер, это верное решение?

2020-06-23 13:40 UTC, NickelGit commented on db/migrate/20200618161155_add_password_reset_columns_to_user.rb
> +    add_column :users, :reset_password_token, :string
В дополнение к проверке уникальности на этапе генерации токена, в модели юзера добавил валидацию на уникальность токена.

2020-06-25 08:15 UTC, NickelGit commented on app/controllers/api/v1/tasks_controller.rb
> +                        task_name: task.name,
Разобрался, простые типы должны передаваться в job сайдкика. Но иного способа передачи данных кроме как так, или объектом не нашел.

2020-06-25 20:43 UTC, pn-y requested changes

2020-06-25 20:43 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +                        task_name: task.name,
👍

2020-06-25 20:43 UTC, pn-y commented on app/helpers/reset_password_helper.rb
> +module ResetPasswordHelper
Бизнес логика в контроллере. Это не хорошо

2020-06-25 20:43 UTC, pn-y commented on app/models/user.rb
> +  validates :reset_password_token, uniqueness: {allow_nil: true, allow_blank: true}
разве allow_blank не покрывает собой allow_nil?

2020-06-25 20:43 UTC, pn-y commented on db/migrate/20200618161155_add_password_reset_columns_to_user.rb
> +    add_column :users, :reset_password_token, :string
Ага, и в базе бы надо иметь это. Ведь валидации на уровне приложения не 100% гарантируют уникальность.

2020-06-26 13:43 UTC, NickelGit commented on app/helpers/reset_password_helper.rb
> +module ResetPasswordHelper
Заменил на набор сервисов вот по этому гайду: https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial

2020-06-30 19:14 UTC, pn-y approved these changes

2020-07-01 06:23 UTC, merged