Feature/sidekiq
NickelGit/TaskManager pull request #35
Opened 2020-06-25 08:15 UTC by NickelGit

2020-06-25 20:32 UTC, pn-y commented
Измени назначение ветки, я вижу изменения с предыдущего задания.

2020-06-25 20:34 UTC, pn-y requested changes

2020-06-25 20:34 UTC, pn-y commented on app/jobs/send_task_create_notification_job.rb
> +    return if task_id.blank?
В каком вообще случае он может быть пустым?

2020-06-25 20:34 UTC, pn-y commented on test/mailers/previews/user_mailer_preview.rb
> +    task = Task.first
Сомнительно что будет только 1 таск

2020-06-26 11:31 UTC, NickelGit commented
> Измени назначение ветки, я вижу изменения с предыдущего задания.

Правильно ли я понял, что данный PR надо мержить в feature/ActionMailer, а не в develop?

2020-06-26 12:37 UTC, NickelGit commented on test/mailers/previews/user_mailer_preview.rb
> +    task = Task.first
У нас же не предусмотренно массовое удаление тасков. Удалять можно только по 1 таску из формы изменения таска.

2020-06-29 06:52 UTC, NickelGit commented on app/jobs/send_task_create_notification_job.rb
> +    return if task_id.blank?
Перенес запросы к базе в джобы. Проверки оставил на случай если в промежутке между запросом(созданием, апдэйтом тасков, или сбросом пароля) и нотификацией об этом действии, объект из базы был удален.

2020-06-30 19:16 UTC, pn-y requested changes

2020-06-30 19:16 UTC, pn-y commented on app/jobs/send_password_reset_notification_job.rb
> +    return if @user.blank?
Строчка бесполезна т.к. в случае отсутствия юзера с айдишником - упадет на 6 строке (и это хорошо)

2020-06-30 19:16 UTC, pn-y commented on app/jobs/send_password_reset_notification_job.rb
> +    @user = User.find(user_id)
Инстанс переменная абсолютно не нужна

2020-06-30 19:16 UTC, pn-y commented on app/jobs/send_password_reset_notification_job.rb
> +    return if @user.blank?
И остальные воркеры глянь

2020-07-06 20:57 UTC, artempartos approved these changes

2020-07-07 06:44 UTC, merged