Models generated and migrated
NickelGit/TaskManager pull request #4
Opened 2020-04-27 14:51 UTC by NickelGit

TaskManager. Модели. >> Генерация моделей

2020-04-28 12:06 UTC, pn-y requested changes

2020-04-28 12:06 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id { 1 }
Если можно не опускаться до уровня something_id - не стоит этого делать.

Factory Bot умеет работать с ассоциациями как с сущностями.

Но их не стоит создавать каждый раз - сделай их пустыми. Это нужно для того что бы не создавалось по 100500 сущностей при вызове фабрики.

Сделай отдельные трейты где бы создавался auther или assignee

2020-04-28 12:06 UTC, pn-y commented on test/factories/tasks.rb
> +    description { "MyText" }
Используй sequence для таких текстовых полей

2020-04-28 12:06 UTC, pn-y commented on test/factories/users.rb
> +    type { "" }
Пустой тип - не валидные данные

2020-04-29 12:43 UTC, Andrew8xx8 commented
Нужно удалить пустые тесты и поправить форматирование в фабрике

2020-04-29 14:27 UTC, Andrew8xx8 approved these changes

2020-04-29 14:41 UTC, merged