State machine added
NickelGit/TaskManager pull request #6
Opened 2020-05-06 08:32 UTC by NickelGit

2020-05-06 10:55 UTC, Andrew8xx8 requested changes

2020-05-06 10:55 UTC, Andrew8xx8 commented on app/models/task.rb
> +    state :in_development do
Опиши все состояния используя `state` выше. А в этом месте нужно использовать `event`

2020-05-06 12:03 UTC, NickelGit commented on app/models/task.rb
> +    state :in_development do
Правильно ли я понял, что нужно создать выше еще один блок state_machine внутрь которого нужно вынести описание всех состояний через state? 
И нужно ли описывать все состояния, или только те для которых должны выполнится определенные действия?
Сейчас делаю только валидацию для статуса :in_development .
Т.е. нужно ли создавать пустые блоки? например:
```
state :in_qa do
end
```

2020-05-07 14:29 UTC, pn-y approved these changes

2020-05-07 14:32 UTC, merged